[build]
base="frontend/"
publish="packages/react-app/build/"

[context.production]
command = "yarn react-app:build"

[context.deploy-preview]
command = 'yarn react-app:build && yarn react-app:echo-netlify-basic-auth'
