version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cct-wallet-ea"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d1o3rciscfi9"
s3_prefix = "cct-wallet-ea"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
